data:
  checkpoint_path: ./checkpoint/
  dev_path: ./data/dev_sampled.csv
  output_path: ./output/
  submission_path: ./data/sample_submission.csv
  test_path: ./data/test.csv
  train_path: ./data/train_sampled.csv
  val_path: ./data/dev.csv
model:
  model_name: team-lucid/deberta-v3-base-korean
train:
  batch_size: 16
  learning_rate: 1e-5
  max_epoch: 10
  shuffle: true
